import { HasanatSourceType } from '../enums/hasanat-source-type.enum';

export const HASANAT_ACTION_RULES = {
  PRAYER_ON_TIME_FARD: {
    key: 'PRAYER_ON_TIME_FARD',
    sourceType: HasanatSourceType.PRAYER,
    points: 25,
    description: 'Priere a l heure Fard',
    isActive: true,
  },
  PRAYER_GROUP: {
    key: 'PRAYER_GROUP',
    sourceType: HasanatSourceType.PRAYER,
    points: 35,
    description: 'Priere en groupe/Jamaa',
    isActive: true,
  },
  PRAYER_MOSQUE: {
    key: 'PRAYER_MOSQUE',
    sourceType: HasanatSourceType.PRAYER,
    points: 40,
    description: 'Priere a la mosquee',
    isActive: true,
  },
  TAHAJJUD: {
    key: 'TAHAJJUD',
    sourceType: HasanatSourceType.PRAYER,
    points: 40,
    description: 'Tahajjud',
    isActive: true,
  },
  QURAN_PAGE: {
    key: 'QURAN_PAGE',
    sourceType: HasanatSourceType.QURAN_READING,
    points: 8,
    description: 'Quran reading per page',
    isActive: true,
  },
  QURAN_OBJECTIVE_REACHED: {
    key: 'QURAN_OBJECTIVE_REACHED',
    sourceType: HasanatSourceType.QURAN_READING,
    points: 15,
    description: 'Quran objective reached',
    isActive: true,
  },
  MORNING_ADHKAR_COMPLETED: {
    key: 'MORNING_ADHKAR_COMPLETED',
    sourceType: HasanatSourceType.DHIKR,
    points: 13,
    description: 'Morning adhkar completed',
    isActive: true,
  },
  EVENING_ADHKAR_COMPLETED: {
    key: 'EVENING_ADHKAR_COMPLETED',
    sourceType: HasanatSourceType.DHIKR,
    points: 13,
    description: 'Evening adhkar completed',
    isActive: true,
  },
  TASBIH_100_MORNING: {
    key: 'TASBIH_100_MORNING',
    sourceType: HasanatSourceType.DHIKR,
    points: 10,
    description: 'Tasbih 100x morning',
    isActive: true,
  },
  TASBIH_100_EVENING: {
    key: 'TASBIH_100_EVENING',
    sourceType: HasanatSourceType.DHIKR,
    points: 10,
    description: 'Tasbih 100x evening',
    isActive: true,
  },
  FASTING_COMPLETED: {
    key: 'FASTING_COMPLETED',
    sourceType: HasanatSourceType.FASTING,
    points: 40,
    description: 'Fasting completed',
    isActive: true,
  },
  CHARITY_ACTION_COMPLETED: {
    key: 'CHARITY_ACTION_COMPLETED',
    sourceType: HasanatSourceType.CHARITY,
    points: 20,
    description: 'Sadaqa / social action',
    isActive: true,
  },
  STREAK_7_BONUS: {
    key: 'STREAK_7_BONUS',
    sourceType: HasanatSourceType.STREAK_BONUS,
    points: 50,
    description: '7-day streak bonus',
    isActive: true,
  },
} as const;
