export enum HasanatSourceType {
  PRAYER = 'PRAYER',
  QURAN_READING = 'QURAN_READING',
  QURAN_GOAL = 'QURAN_GOAL',
  DHIKR = 'DHIKR',
  FASTING = 'FASTING',
  CHARITY = 'CHARITY',
  STREAK_BONUS = 'STREAK_BONUS',
  MANUAL_ADJUSTMENT = 'MANUAL_ADJUSTMENT',
}
