export enum CharityActionType {
  SADAQA = 'SADAQA',
  MARAUDE = 'MARAUDE',
  COLLECTE = 'COLLECTE',
  DISTRIBUTION = 'DISTRIBUTION',
  VISITE = 'VISITE',
  PARRAINAGE = 'PARRAINAGE',
  MENTORAT = 'MENTORAT',
  RANDONNEE_SOLIDAIRE = 'RANDONNEE_SOLIDAIRE',
  COURSE_SOLIDAIRE = 'COURSE_SOLIDAIRE',
  VOYAGE_SOLIDAIRE = 'VOYAGE_SOLIDAIRE',
  OTHER = 'OTHER',
}
