import { Injectable, NotFoundException } from '@nestjs/common';
import { DataSource, Repository } from 'typeorm';
import { GroupsPersistencePort } from '../../../domain/groups/ports/groups-persistence.port';
import { GoalProgressTypeormEntity } from '../../goals/entities/goal-progress.typeorm-entity';
import { GroupEncouragementTypeormEntity } from '../entities/group-encouragement.typeorm-entity';
import { GroupMemberTypeormEntity } from '../entities/group-member.typeorm-entity';
import { GroupTypeormEntity } from '../entities/group.typeorm-entity';
@Injectable() export class GroupsTypeormAdapter implements GroupsPersistencePort {
  private readonly groups: Repository<GroupTypeormEntity>; private readonly members: Repository<GroupMemberTypeormEntity>; private readonly encouragements: Repository<GroupEncouragementTypeormEntity>; private readonly progress: Repository<GoalProgressTypeormEntity>; constructor(dataSource: DataSource) { this.groups = dataSource.getRepository(GroupTypeormEntity); this.members = dataSource.getRepository(GroupMemberTypeormEntity); this.encouragements = dataSource.getRepository(GroupEncouragementTypeormEntity); this.progress = dataSource.getRepository(GoalProgressTypeormEntity); }
  findById(id: string) { return this.groups.findOne({ where: { id } }) as any; } findByInviteCode(inviteCode: string) { return this.groups.findOne({ where: { inviteCode, isActive: true } }) as any; } create(data: any) { return this.groups.save(this.groups.create(data) as any) as any; } async update(id: string, data: any) { const existing = await this.groups.findOne({ where: { id } }); if (!existing) throw new NotFoundException('Group not found'); return this.groups.save({ ...existing, ...data }); }
  findMember(groupId: string, userId: string) { return this.members.findOne({ where: { groupId, userId } }); } findMemberships(userId: string) { return this.members.find({ where: { userId }, order: { createdAt: 'DESC' } }); } createMember(data: any) { return this.members.save(this.members.create(data) as any) as any; } async updateMember(id: string, data: any) { const existing = await this.members.findOne({ where: { id } }); if (!existing) throw new NotFoundException('Group member not found'); return this.members.save({ ...existing, ...data }); } findMembers(groupId: string) { return this.members.find({ where: { groupId } }); } createEncouragement(data: any) { return this.encouragements.save(this.encouragements.create(data) as any) as any; } findEncouragements(groupId: string) { return this.encouragements.find({ where: { groupId }, order: { createdAt: 'DESC' } }); } findAllProgress() { return this.progress.find({ order: { createdAt: 'DESC' } }); }
}
