export interface PrayerTimeModel {
  id: string;
  userId: string;
  prayerDate: string;
  timezone: string;
  city?: string | null;
  country?: string | null;
  latitude: number | string;
  longitude: number | string;
  calculationMethod: string;
  madhab: string;
  imsak?: string | null;
  fajr: string;
  sunrise?: string | null;
  dhuhr: string;
  asr: string;
  maghrib: string;
  isha: string;
  imsakDateTime?: string | null;
  fajrDateTime?: string | null;
  sunriseDateTime?: string | null;
  dhuhrDateTime?: string | null;
  asrDateTime?: string | null;
  maghribDateTime?: string | null;
  ishaDateTime?: string | null;
  currentPrayer?: string | null;
  nextPrayer?: string | null;
  timeUntilNext?: string | null;
  minutesUntilNext?: number | null;
  source: string;
  rawResponse?: Record<string, unknown> | null;
  createdAt?: Date;
  updatedAt?: Date;
}
