export enum FastingType {
  MONDAY = 'MONDAY',
  THURSDAY = 'THURSDAY',
  WHITE_DAYS = 'WHITE_DAYS',
  ARAFAH = 'ARAFAH',
  ASHURA = 'ASHURA',
  RAMADAN = 'RAMADAN',
  CUSTOM = 'CUSTOM',
  OTHER = 'OTHER',
}
