export enum NotificationType {
  DAILY_VERSE = 'DAILY_VERSE',
  DAILY_HADITH = 'DAILY_HADITH',
  PRAYER = 'PRAYER',
  FASTING = 'FASTING',
  DHIKR = 'DHIKR',
  QURAN = 'QURAN',
  ENCOURAGEMENT = 'ENCOURAGEMENT',
  TEST = 'TEST',
}
