export enum MainIntention {
  COMMUNITY_ENGAGEMENT = 'COMMUNITY_ENGAGEMENT',
  PRAYER_CONSISTENCY = 'PRAYER_CONSISTENCY',
  FIVE_DAILY_PRAYERS = 'FIVE_DAILY_PRAYERS',
  QURAN_READING_PROGRESS = 'QURAN_READING_PROGRESS',
  QURAN_MEMORIZATION_PROGRESS = 'QURAN_MEMORIZATION_PROGRESS',
  DAILY_INVOCATIONS = 'DAILY_INVOCATIONS',
  REGULAR_FASTING = 'REGULAR_FASTING',
  DEEPEN_SPIRITUALITY = 'DEEPEN_SPIRITUALITY',
  DEEPEN_WORSHIP = 'DEEPEN_WORSHIP',
  PRACTICE_CONSISTENCY = 'PRACTICE_CONSISTENCY',
  SPIRITUAL_BALANCE = 'SPIRITUAL_BALANCE',
  CLOSENESS_TO_ALLAH = 'CLOSENESS_TO_ALLAH',
}
